name = "nexttrainworker"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "SCHEDULE_KV"
id = "df8cce3477aa40f3a473f618d7fcb343"
preview_id = "3c50290fbef540bb83e9c2018ec3ab70"

[[kv_namespaces]]
binding = "ARRIVALS_KV"
id = "89572bd8828c45a0baff91b5b3da6d17"
preview_id = "d82f08d8f756408fa2afa21bf4be5a0e"
