import { buildSchedule } from '../src/gtfs/schedule-build.js';
import { writeFileSync } from 'fs';

const TEMPLATE_TS = 'src/template.generated.ts';
const STATIONS_TS = 'src/stations.generated.ts';

function toB64(bytes: Uint8Array): string {
  let bin = '';
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return Buffer.from(bin, 'binary').toString('base64');
}

function decodeB64Snippet(): string {
  return `function _b64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}`;
}

function emitTemplateModule(templateBin: Uint8Array, hashOffsets: Uint32Array, version: string): string {
  const tB64 = toB64(templateBin);
  const hBytes = new Uint8Array(hashOffsets.buffer, hashOffsets.byteOffset, hashOffsets.byteLength);
  const hB64 = toB64(hBytes);
  return `// AUTO-GENERATED by scripts/seed-schedule.ts. Do not edit by hand.
// version: ${version}  template: ${templateBin.length}B  entries: ${hashOffsets.length >> 1}

${decodeB64Snippet()}

export const TEMPLATE_BYTES: Uint8Array = _b64("${tB64}");
export const TEMPLATE_VERSION = "${version}";

export const HASH_OFFSETS: Map<number, number[]> = (() => {
  const raw = _b64("${hB64}");
  const v = new Uint32Array(raw.buffer, raw.byteOffset, raw.byteLength >>> 2);
  const m = new Map<number, number[]>();
  for (let i = 0; i < v.length; i += 2) {
    const h = v[i]; const o = v[i + 1];
    let a = m.get(h); if (!a) { a = []; m.set(h, a); } a.push(o);
  }
  return m;
})();
`;
}

function emitStationsModule(stationsBin: Uint8Array, version: string): string {
  const b64 = toB64(stationsBin);
  return `// AUTO-GENERATED by scripts/seed-schedule.ts. Do not edit by hand.
// version: ${version}  size: ${stationsBin.length}B

${decodeB64Snippet()}

export const STATIONS_BYTES: Uint8Array = _b64("${b64}");
`;
}

async function main() {
  console.log('[seed] Building schedule...');
  const { generatedAt, templateBin, hashOffsets, stationsBin } = await buildSchedule();
  console.log(`[seed] Built — template=${(templateBin.length / 1024).toFixed(1)}KB  hashOffsets=${hashOffsets.length >> 1} pairs  stations=${(stationsBin.length / 1024).toFixed(1)}KB`);

  const version = String(generatedAt);

  writeFileSync(TEMPLATE_TS, emitTemplateModule(templateBin, hashOffsets, version));
  console.log(`[seed] Wrote ${TEMPLATE_TS}`);

  writeFileSync(STATIONS_TS, emitStationsModule(stationsBin, version));
  console.log(`[seed] Wrote ${STATIONS_TS}`);

  console.log(`[seed] Done. version=${version}`);
}

main().catch(err => { console.error(err); process.exit(1); });
