import { buildSchedule } from "../src/build/schedule.js";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const GENERATED_DIR = "src/worker/generated";

function b64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

function emitOffsets(
  templateBin: Uint8Array,
  tripOffsets: Map<string, number[]>,
  stopOffsets: Map<string, Map<string, number[]>>,
  version: string,
): string {
  const tB64 = b64(templateBin);

  // Build TRIP_OFFSETS entries
  const tripLines: string[] = [];
  for (const [tripId, offs] of tripOffsets) {
    const escaped = tripId.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    tripLines.push(`  ["${escaped}", new Uint32Array([${offs.join(",")}])]`);
  }

  // Build STOP_OFFSETS entries as plain nested arrays (consumed by _buildSO)
  const stopLines: string[] = [];
  for (const [tripId, inner] of stopOffsets) {
    const escapedTrip = tripId.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
    const innerLines: string[] = [];
    for (const [stopId, offs] of inner) {
      const escapedStop = stopId.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      innerLines.push(`    ["${escapedStop}", [${offs.join(",")}]]`);
    }
    stopLines.push(
      `  ["${escapedTrip}", [\n${innerLines.join(",\n")}\n  ]]`,
    );
  }

  return `// AUTO-GENERATED by scripts/seed-schedule.ts — do not edit
// version: ${version}  template: ${templateBin.length}B  trips: ${tripOffsets.size}  stops: ${stopOffsets.size}

function _b64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const TEMPLATE_BYTES: Uint8Array = _b64("${tB64}");

export const TRIP_OFFSETS: ReadonlyMap<string, Uint32Array> = new Map<string, Uint32Array>([
${tripLines.join(",\n")}
]);

function _buildSO(
  pairs: [string, [string, number[]][]][],
): ReadonlyMap<string, ReadonlyMap<string, Uint32Array>> {
  const m = new Map<string, ReadonlyMap<string, Uint32Array>>();
  for (let i = 0; i < pairs.length; i++) {
    const [tid, stops] = pairs[i];
    const inner = new Map<string, Uint32Array>();
    for (let j = 0; j < stops.length; j++) {
      inner.set(stops[j][0], new Uint32Array(stops[j][1]));
    }
    m.set(tid, inner);
  }
  return m;
}

export const STOP_OFFSETS: ReadonlyMap<string, ReadonlyMap<string, Uint32Array>> = _buildSO([
${stopLines.join(",\n")}
]);
`;
}

function emitStations(stationsBin: Uint8Array, version: string): string {
  const sB64 = b64(stationsBin);
  return `// AUTO-GENERATED by scripts/seed-schedule.ts — do not edit
// version: ${version}  size: ${stationsBin.length}B

function _b64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const STATIONS_BYTES: Uint8Array = _b64("${sB64}");
`;
}

async function main(): Promise<void> {
  console.log("[seed] Building schedule...");
  const { generatedAt, templateBin, tripOffsets, stopOffsets, stationsBin } = await buildSchedule();
  console.log(
    `[seed] Built — template=${(templateBin.length / 1024).toFixed(1)}KB` +
    `  trips=${tripOffsets.size}  stops=${stopOffsets.size}` +
    `  stations=${(stationsBin.length / 1024).toFixed(1)}KB`,
  );

  const version = String(generatedAt);
  mkdirSync(join(GENERATED_DIR), { recursive: true });

  const offsetsPath = join(GENERATED_DIR, "offsets.ts");
  writeFileSync(offsetsPath, emitOffsets(templateBin, tripOffsets, stopOffsets, version));
  console.log(`[seed] Wrote ${offsetsPath}`);

  const stationsPath = join(GENERATED_DIR, "stations.ts");
  writeFileSync(stationsPath, emitStations(stationsBin, version));
  console.log(`[seed] Wrote ${stationsPath}`);

  console.log(`[seed] Done. version=${version}`);
}

main().catch((err: unknown) => { console.error(err); process.exit(1); });
