import { buildSchedule } from "../src/build/schedule.js";
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const GENERATED_DIR = "src/worker/generated";
const ROUTE_IDS_PATH = "src/worker/route-ids.ts";

function b64(bytes: Uint8Array): string {
  return Buffer.from(bytes).toString("base64");
}

function buildOffsetsBinary(
  tripOffsets: Map<string, number[]>,
  stopOffsets: Map<string, Map<string, number[]>>,
  stopToSlug: Map<string, string>,
): Uint8Array {
  const enc = new TextEncoder();

  // Pre-encode all strings once
  const tripIds = new Map<string, Uint8Array>();
  for (const k of tripOffsets.keys()) tripIds.set(k, enc.encode(k));
  for (const k of stopOffsets.keys()) if (!tripIds.has(k)) tripIds.set(k, enc.encode(k));

  const stopIds = new Map<string, Uint8Array>();
  for (const inner of stopOffsets.values()) for (const k of inner.keys()) if (!stopIds.has(k)) stopIds.set(k, enc.encode(k));
  for (const k of stopToSlug.keys()) if (!stopIds.has(k)) stopIds.set(k, enc.encode(k));

  const slugStrs = new Map<string, Uint8Array>();
  for (const v of stopToSlug.values()) if (!slugStrs.has(v)) slugStrs.set(v, enc.encode(v));

  // Calculate total size
  let size = 0;
  // TRIP_OFFSETS section
  size += 4;
  for (const [id, offs] of tripOffsets) size += 2 + tripIds.get(id)!.length + 1 + offs.length * 4;
  // STOP_OFFSETS section
  size += 4;
  for (const [tid, inner] of stopOffsets) {
    size += 2 + tripIds.get(tid)!.length + 2;
    for (const [sid, offs] of inner) size += 2 + stopIds.get(sid)!.length + 1 + offs.length * 4;
  }
  // STOP_ID_TO_SLUG section
  size += 4;
  for (const [stopId, slug] of stopToSlug) size += 2 + stopIds.get(stopId)!.length + 2 + slugStrs.get(slug)!.length;

  const buf = new Uint8Array(size);
  const view = new DataView(buf.buffer);
  let p = 0;
  const u8 = (v: number) => { buf[p++] = v; };
  const u16 = (v: number) => { view.setUint16(p, v, true); p += 2; };
  const u32 = (v: number) => { view.setUint32(p, v, true); p += 4; };
  const bytes = (b: Uint8Array) => { buf.set(b, p); p += b.length; };
  const str = (b: Uint8Array) => { u16(b.length); bytes(b); };

  // TRIP_OFFSETS
  u32(tripOffsets.size);
  for (const [id, offs] of tripOffsets) {
    str(tripIds.get(id)!);
    u8(offs.length);
    for (const o of offs) u32(o);
  }

  // STOP_OFFSETS
  u32(stopOffsets.size);
  for (const [tid, inner] of stopOffsets) {
    str(tripIds.get(tid)!);
    u16(inner.size);
    for (const [sid, offs] of inner) {
      str(stopIds.get(sid)!);
      u8(offs.length);
      for (const o of offs) u32(o);
    }
  }

  // STOP_ID_TO_SLUG
  u32(stopToSlug.size);
  for (const [stopId, slug] of stopToSlug) {
    str(stopIds.get(stopId)!);
    str(slugStrs.get(slug)!);
  }

  return buf;
}

function emitOffsets(
  templateBin: Uint8Array,
  tripOffsets: Map<string, number[]>,
  stopOffsets: Map<string, Map<string, number[]>>,
  stopToSlug: Map<string, string>,
  version: string,
): string {
  const tB64 = b64(templateBin);
  const offsetsBin = buildOffsetsBinary(tripOffsets, stopOffsets, stopToSlug);
  const oB64 = b64(offsetsBin);

  return `// AUTO-GENERATED by scripts/seed-schedule.ts — do not edit
// version: ${version}  template: ${templateBin.length}B  trips: ${tripOffsets.size}  stops: ${stopOffsets.size}

function _b64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const TEMPLATE_BYTES: Uint8Array = _b64("${tB64}");

function _decodeOffsets(buf: Uint8Array): {
  trips: ReadonlyMap<string, Uint32Array>;
  stops: ReadonlyMap<string, ReadonlyMap<string, Uint32Array>>;
  slugs: ReadonlyMap<string, string>;
} {
  const dec = new TextDecoder();
  const v = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  let p = 0;
  const u8 = () => buf[p++];
  const u16 = () => { const n = v.getUint16(p, true); p += 2; return n; };
  const u32 = () => { const n = v.getUint32(p, true); p += 4; return n; };
  const str = () => { const l = u16(); const s = dec.decode(buf.subarray(p, p + l)); p += l; return s; };

  const tripCount = u32();
  const trips = new Map<string, Uint32Array>();
  for (let i = 0; i < tripCount; i++) {
    const id = str();
    const n = u8();
    const offs = new Uint32Array(n);
    for (let j = 0; j < n; j++) offs[j] = u32();
    trips.set(id, offs);
  }

  const stopTripCount = u32();
  const stops = new Map<string, ReadonlyMap<string, Uint32Array>>();
  for (let i = 0; i < stopTripCount; i++) {
    const tid = str();
    const stopCount = u16();
    const inner = new Map<string, Uint32Array>();
    for (let j = 0; j < stopCount; j++) {
      const sid = str();
      const n = u8();
      const offs = new Uint32Array(n);
      for (let k = 0; k < n; k++) offs[k] = u32();
      inner.set(sid, offs);
    }
    stops.set(tid, inner);
  }

  const slugCount = u32();
  const slugs = new Map<string, string>();
  for (let i = 0; i < slugCount; i++) {
    slugs.set(str(), str());
  }

  return { trips, stops, slugs };
}

const { trips: _t, stops: _s, slugs: _sl } = _decodeOffsets(_b64("${oB64}"));

export const TRIP_OFFSETS: ReadonlyMap<string, Uint32Array> = _t;
export const STOP_OFFSETS: ReadonlyMap<string, ReadonlyMap<string, Uint32Array>> = _s;
export const STOP_ID_TO_SLUG: ReadonlyMap<string, string> = _sl;
`;
}

function emitStations(stationsBin: Uint8Array, version: string): string {
  const sB64 = b64(stationsBin);
  return `// AUTO-GENERATED by scripts/seed-schedule.ts — do not edit
// version: ${version}  size: ${stationsBin.length}B

function _b64(s: string): Uint8Array {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

export const STATIONS_BYTES: Uint8Array = _b64("${sB64}");
`;
}

function emitRouteIds(routeIdToShortName: Map<string, string>): string {
  const entries = [...routeIdToShortName.entries()]
    .map(([k, v]) => `  "${k}": "${v}"`)
    .join(",\n");
  return `// AUTO-UPDATED by scripts/seed-schedule.ts — reflects current RTD GTFS rail routes.
// Maps raw GTFS route_id → display short name.

export const ROUTE_ID_TO_SHORT_NAME: Readonly<Record<string, string>> = {
${entries}
};
`;
}

async function main(): Promise<void> {
  console.log("[seed] Building schedule...");
  const { generatedAt, templateBin, tripOffsets, stopOffsets, stopToSlug, stationsBin, routeIdToShortName } = await buildSchedule();
  console.log(
    `[seed] Built — template=${(templateBin.length / 1024).toFixed(1)}KB` +
    `  trips=${tripOffsets.size}  stops=${stopOffsets.size}` +
    `  slugs=${stopToSlug.size}  stations=${(stationsBin.length / 1024).toFixed(1)}KB`,
  );

  const version = String(generatedAt);
  mkdirSync(join(GENERATED_DIR), { recursive: true });

  const offsetsPath = join(GENERATED_DIR, "offsets.ts");
  writeFileSync(offsetsPath, emitOffsets(templateBin, tripOffsets, stopOffsets, stopToSlug, version));
  console.log(`[seed] Wrote ${offsetsPath}`);

  const stationsPath = join(GENERATED_DIR, "stations.ts");
  writeFileSync(stationsPath, emitStations(stationsBin, version));
  console.log(`[seed] Wrote ${stationsPath}`);

  writeFileSync(ROUTE_IDS_PATH, emitRouteIds(routeIdToShortName));
  console.log(`[seed] Wrote ${ROUTE_IDS_PATH}`);

  console.log(`[seed] Done. version=${version}`);
}

main().catch((err: unknown) => { console.error(err); process.exit(1); });
