/**
 * alerts/current.bin layout (Stored in R2, generated by Worker):
 *   [u32 generated_at]
 *   [u8 route_count]
 *   per route:
 *     [u8 name_len][name UTF-8]         // "A", "B", ...
 *     [u8 alert_count]
 *     per alert:
 *       [u32 active_from]               // unix seconds, 0 if unspecified
 *       [u32 active_until]              // unix seconds, 0 if unspecified
 *       [u8 cause][u8 effect]
 *       [u8 header_len][header UTF-8]   // capped 200B
 *       [u16 desc_len][desc UTF-8]      // capped 512B
 */

import type { ParsedAlert } from "../live/alerts-decode.js";
import { ROUTE_ID_TO_SHORT_NAME } from "../route-ids.js";

const RAIL_TYPES = new Set([0, 2]);
const _te = new TextEncoder();
const _td = new TextDecoder();

// Precompute the set of all known rail short names for wildcard fan-out.
const ALL_SHORT_NAMES: ReadonlySet<string> = new Set(Object.values(ROUTE_ID_TO_SHORT_NAME));

class BufWriter {
  private buf: Uint8Array;
  private pos = 0;

  constructor(initial = 512) {
    this.buf = new Uint8Array(initial);
  }

  private grow(needed: number): void {
    if (this.pos + needed <= this.buf.length) return;
    let cap = this.buf.length;
    while (cap < this.pos + needed) cap *= 2;
    const next = new Uint8Array(cap);
    next.set(this.buf.subarray(0, this.pos));
    this.buf = next;
  }

  writeU8(v: number): void {
    this.grow(1);
    this.buf[this.pos++] = v & 0xFF;
  }

  writeU16(v: number): void {
    this.grow(2);
    this.buf[this.pos++] = v & 0xFF;
    this.buf[this.pos++] = (v >>> 8) & 0xFF;
  }

  writeU32(v: number): void {
    this.grow(4);
    this.buf[this.pos++] = v & 0xFF;
    this.buf[this.pos++] = (v >>> 8) & 0xFF;
    this.buf[this.pos++] = (v >>> 16) & 0xFF;
    this.buf[this.pos++] = (v >>> 24) & 0xFF;
  }

  writeBytes(bytes: Uint8Array): void {
    this.grow(bytes.length);
    this.buf.set(bytes, this.pos);
    this.pos += bytes.length;
  }

  finish(): Uint8Array {
    return this.buf.subarray(0, this.pos);
  }
}

export function buildAlertsBin(alerts: ParsedAlert[], generatedAt: number): Uint8Array {
  const byRoute = new Map<string, Set<ParsedAlert>>();

  for (const alert of alerts) {
    if (alert.cause === 9 || alert.activeFrom === 0) continue;

    const shortNames = new Set<string>();
    for (const rid of alert.routeIds) {
      const sn = ROUTE_ID_TO_SHORT_NAME[rid];
      if (sn) shortNames.add(sn);
    }
    if (shortNames.size === 0) {
      for (const rt of alert.routeTypes) {
        if (RAIL_TYPES.has(rt)) { shortNames.add("*"); break; }
      }
    }
    for (const sn of shortNames) {
      let bucket = byRoute.get(sn);
      if (!bucket) { bucket = new Set(); byRoute.set(sn, bucket); }
      bucket.add(alert);
    }
  }

  // Fan out wildcard alerts to all known rail short names
  const wildcardAlerts = byRoute.get("*");
  if (wildcardAlerts) {
    byRoute.delete("*");
    for (const sn of ALL_SHORT_NAMES) {
      let bucket = byRoute.get(sn);
      if (!bucket) { bucket = new Set(); byRoute.set(sn, bucket); }
      for (const a of wildcardAlerts) bucket.add(a);
    }
  }

  const routeNames = [...byRoute.keys()].sort();
  const w = new BufWriter();
  w.writeU32(generatedAt);
  w.writeU8(Math.min(routeNames.length, 255));

  for (const routeName of routeNames) {
    const bucket = byRoute.get(routeName) ?? new Set<ParsedAlert>();
    const nameBytes = _te.encode(routeName);
    w.writeU8(nameBytes.length & 0xFF);
    w.writeBytes(nameBytes);
    w.writeU8(Math.min(bucket.size, 255));
    for (const alert of bucket) {
      w.writeU32(alert.activeFrom);
      w.writeU32(alert.activeUntil);
      w.writeU8(alert.cause);
      w.writeU8(alert.effect);
      const hBytes = _te.encode(alert.header.slice(0, 200));
      w.writeU8(Math.min(hBytes.length, 255));
      w.writeBytes(hBytes.subarray(0, 255));
      const dBytes = _te.encode(alert.description.slice(0, 512));
      const dLen = Math.min(dBytes.length, 65535);
      w.writeU16(dLen);
      w.writeBytes(dBytes.subarray(0, dLen));
    }
  }

  return w.finish();
}

/** Returns encoded response bytes for the /al (no route) summary. */
export function scanAlertsSummaryBytes(bin: Uint8Array): Uint8Array | null {
  if (bin.length < 5) return null;
  let pos = 4; // skip generated_at
  const routeCount = bin[pos++];
  const out: number[] = [routeCount];

  for (let i = 0; i < routeCount; i++) {
    const nlen = bin[pos++];
    out.push(nlen);
    for (let j = 0; j < nlen; j++) out.push(bin[pos++]);
    const alertCount = bin[pos++];
    out.push(alertCount);
    for (let j = 0; j < alertCount; j++) {
      pos += 10; // active_from u32 + active_until u32 + cause u8 + effect u8
      const hlen = bin[pos++]; pos += hlen;
      const dlen = bin[pos++] | (bin[pos++] << 8); pos += dlen;
    }
  }

  return new Uint8Array(out);
}

/** Returns encoded response bytes for the /al?r=ROUTE detail view. */
export function scanAlertsByRouteBytes(
  bin: Uint8Array,
  targetRoute: string,
): Uint8Array | null {
  if (bin.length < 5) return null;
  let pos = 4; // skip generated_at
  const routeCount = bin[pos++];

  for (let i = 0; i < routeCount; i++) {
    const nlen = bin[pos++];
    let route = "";
    for (let j = 0; j < nlen; j++) route += String.fromCharCode(bin[pos++]);
    const alertCount = bin[pos++];

    if (route !== targetRoute) {
      for (let j = 0; j < alertCount; j++) {
        pos += 10;
        const hlen = bin[pos++]; pos += hlen;
        const dlen = bin[pos++] | (bin[pos++] << 8); pos += dlen;
      }
      continue;
    }

    const out: number[] = [alertCount];
    for (let j = 0; j < alertCount; j++) {
      const activeFrom  = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
      const activeUntil = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
      const cause  = bin[pos++];
      const effect = bin[pos++];
      const hlen   = bin[pos++];
      const header = _td.decode(bin.subarray(pos, pos + hlen)); pos += hlen;
      const dlen   = bin[pos++] | (bin[pos++] << 8);
      const description = _td.decode(bin.subarray(pos, pos + dlen)); pos += dlen;

      out.push(
        activeFrom & 0xFF, (activeFrom >>> 8) & 0xFF,
        (activeFrom >>> 16) & 0xFF, (activeFrom >>> 24) & 0xFF,
        activeUntil & 0xFF, (activeUntil >>> 8) & 0xFF,
        (activeUntil >>> 16) & 0xFF, (activeUntil >>> 24) & 0xFF,
        cause & 0xFF,
        effect & 0xFF,
      );
      const hb = _te.encode(header);
      out.push(Math.min(hb.length, 255));
      for (const b of hb.subarray(0, 255)) out.push(b);
      const db = _te.encode(description);
      const dbLen = Math.min(db.length, 65535);
      out.push(dbLen & 0xFF, (dbLen >>> 8) & 0xFF);
      for (const b of db.subarray(0, dbLen)) out.push(b);
    }
    return new Uint8Array(out);
  }

  return null;
}
