/**
 * alerts/current.bin layout (Stored in R2, generated by Worker):
 *   [u32 generated_at]
 *   [u8 route_count]
 *   per route:
 *     [u8 name_len][name UTF-8]         // "A", "B", ...
 *     [u8 alert_count]
 *     per alert:
 *       [u32 active_from]               // unix seconds, 0 if unspecified
 *       [u32 active_until]              // unix seconds, 0 if unspecified
 *       [u8 cause][u8 effect]
 *       [u8 header_len][header UTF-8]   // capped 200B
 *       [u16 desc_len][desc UTF-8]      // capped 512B
 */

import type { ParsedAlert } from "../live/alerts-decode.js";
import { ROUTE_ID_TO_SHORT_NAME } from "../route-ids.js";

const RAIL_TYPES = new Set([0, 2]);

export interface AlertSummaryEntry { route: string; count: number; }
export interface AlertDetail {
  activeFrom: number;
  activeUntil: number;
  cause: number;
  effect: number;
  header: string;
  description: string;
}

function w8(buf: number[], v: number): void { buf.push(v & 0xFF); }
function w16(buf: number[], v: number): void { buf.push(v & 0xFF, (v >>> 8) & 0xFF); }
function w32(buf: number[], v: number): void {
  buf.push(v & 0xFF, (v >>> 8) & 0xFF, (v >>> 16) & 0xFF, (v >>> 24) & 0xFF);
}

export function buildAlertsBin(alerts: ParsedAlert[], generatedAt: number): Uint8Array {
  const byRoute = new Map<string, ParsedAlert[]>();

  for (const alert of alerts) {
    if (alert.cause === 9 || alert.activeFrom === 0) continue;

    const shortNames = new Set<string>();
    for (const rid of alert.routeIds) {
      const sn = ROUTE_ID_TO_SHORT_NAME[rid];
      if (sn) shortNames.add(sn);
    }
    if (shortNames.size === 0) {
      for (const rt of alert.routeTypes) {
        if (RAIL_TYPES.has(rt)) { shortNames.add("*"); break; }
      }
    }
    for (const sn of shortNames) {
      let bucket = byRoute.get(sn);
      if (!bucket) { bucket = []; byRoute.set(sn, bucket); }
      bucket.push(alert);
    }
  }

  // Fan out wildcard alerts to all known rail short names
  const wildcardAlerts = byRoute.get("*");
  if (wildcardAlerts) {
    byRoute.delete("*");
    const allShortNames = new Set(Object.values(ROUTE_ID_TO_SHORT_NAME));
    for (const sn of allShortNames) {
      let bucket = byRoute.get(sn);
      if (!bucket) { bucket = []; byRoute.set(sn, bucket); }
      for (const a of wildcardAlerts) if (!bucket.includes(a)) bucket.push(a);
    }
  }

  const routeNames = [...byRoute.keys()].sort();
  const buf: number[] = [];
  w32(buf, generatedAt);
  w8(buf, Math.min(routeNames.length, 255));

  for (const routeName of routeNames) {
    const bucket = byRoute.get(routeName)!;
    const nameBytes = routeName.length & 0xFF;
    buf.push(nameBytes);
    for (let i = 0; i < routeName.length; i++) buf.push(routeName.charCodeAt(i) & 0xFF);
    w8(buf, Math.min(bucket.length, 255));
    for (const alert of bucket) {
      w32(buf, alert.activeFrom);
      w32(buf, alert.activeUntil);
      w8(buf, alert.cause);
      w8(buf, alert.effect);
      const hBytes = new TextEncoder().encode(alert.header.slice(0, 200));
      w8(buf, Math.min(hBytes.length, 255));
      for (const b of hBytes) buf.push(b);
      const dBytes = new TextEncoder().encode(alert.description.slice(0, 512));
      w16(buf, Math.min(dBytes.length, 65535));
      for (const b of dBytes) buf.push(b);
    }
  }

  return new Uint8Array(buf);
}

export function scanAlertsSummary(bin: Uint8Array): { generatedAt: number; routes: AlertSummaryEntry[] } | null {
  if (bin.length < 5) return null;
  let pos = 0;
  const generatedAt = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
  const routeCount = bin[pos++];
  const routes: AlertSummaryEntry[] = [];

  for (let i = 0; i < routeCount; i++) {
    const nlen = bin[pos++];
    let route = "";
    for (let j = 0; j < nlen; j++) route += String.fromCharCode(bin[pos++]);
    const alertCount = bin[pos++];
    routes.push({ route, count: alertCount });
    for (let j = 0; j < alertCount; j++) {
      pos += 10; // active_from u32 + active_until u32 + cause u8 + effect u8
      const hlen = bin[pos++]; pos += hlen;
      const dlen = bin[pos++] | (bin[pos++] << 8); pos += dlen;
    }
  }

  return { generatedAt, routes };
}

export function scanAlertsByRoute(
  bin: Uint8Array,
  targetRoute: string,
): { generatedAt: number; alerts: AlertDetail[] } | null {
  if (bin.length < 5) return null;
  let pos = 0;
  const generatedAt = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
  const routeCount = bin[pos++];

  for (let i = 0; i < routeCount; i++) {
    const nlen = bin[pos++];
    let route = "";
    for (let j = 0; j < nlen; j++) route += String.fromCharCode(bin[pos++]);
    const alertCount = bin[pos++];

    if (route !== targetRoute) {
      for (let j = 0; j < alertCount; j++) {
        pos += 10;
        const hlen = bin[pos++]; pos += hlen;
        const dlen = bin[pos++] | (bin[pos++] << 8); pos += dlen;
      }
      continue;
    }

    const alerts: AlertDetail[] = [];
    const td = new TextDecoder();
    for (let j = 0; j < alertCount; j++) {
      const activeFrom  = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
      const activeUntil = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
      const cause  = bin[pos++];
      const effect = bin[pos++];
      const hlen   = bin[pos++];
      const header = td.decode(bin.subarray(pos, pos + hlen)); pos += hlen;
      const dlen   = bin[pos++] | (bin[pos++] << 8);
      const description = td.decode(bin.subarray(pos, pos + dlen)); pos += dlen;
      alerts.push({ activeFrom, activeUntil, cause, effect, header, description });
    }
    return { generatedAt, alerts };
  }

  return null;
}
