/**
 * Binary encoding/decoding for the arrivals and baseline wire formats.
 *
 * baseline.bin layout (Stored in KV, generated by GitHub):
 *   [u32 generated_at]
 *   [u32 base_midnight_utc]
 *   [u16 dict_count]
 *   dictionary: dict_count × ([u8 len][chars])
 *   [u16 station_count]
 *   index: station_count × ([u8 slug_len][slug][u32 data_offset])
 *   data: per station: [u16 count] × ([u8 route_idx][u8 dir][u16 mono_mins][u32 trip_id_hash])
 *
 * arrivals/current.bin layout (Stored in R2, generated by Worker):
 *   [u32 generated_at]
 *   [u16 dict_count]
 *   dictionary: dict_count × ([u8 len][chars])
 *   [u16 num_stations]
 *   index: num_stations × ([u8 slug_len][slug][u32 data_offset])
 *   data:  per station: [u16 count] × ([u8 route_idx][u8 dir][u16 predicted_mins][s8 delay_status])
 *
 * arrivals/stations.bin: (Stored in KV/R2, generated by GitHub)
 *   [u32 generated_at][u16 station_count]
 *   per station: [lpStr slug][u8 route_count] × ([u8 r,g,b][lpStr route][u8 dir][lpStr headsign])
 */

export interface StationWire {
  k: string;
  r: Array<{ r: string; c: string | null; d: string; h: string }>;
}

// ─── Low-level writers ────────────────────────────────────────────────────────

export function w8(buf: number[], v: number): void { buf.push(v & 0xFF); }
export function w16be(buf: number[], v: number): void { buf.push((v >>> 8) & 0xFF, v & 0xFF); }
export function w32be(buf: number[], v: number): void {
  buf.push((v >>> 24) & 0xFF, (v >>> 16) & 0xFF, (v >>> 8) & 0xFF, v & 0xFF);
}
export function wLpStr(buf: number[], s: string, maxLen: number): void {
  const t = s.slice(0, maxLen);
  buf.push(Math.min(t.length, 255));
  for (let i = 0; i < t.length; i++) buf.push(t.charCodeAt(i) & 0xFF);
}

export function hexToRgb(c: string | null): { r: number; g: number; b: number } {
  if (!c) return { r: 0x88, g: 0x88, b: 0x88 };
  const v = parseInt(c.replace("#", ""), 16);
  if (isNaN(v)) return { r: 0x88, g: 0x88, b: 0x88 };
  return { r: (v >>> 16) & 0xFF, g: (v >>> 8) & 0xFF, b: v & 0xFF };
}

// ─── Hash for Trip IDs (32-bit FNV-1a) ────────────────────────────────────────

export function hashTripId(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

// ─── Dictionary Encoding ──────────────────────────────────────────────────────

export class Dictionary {
  map = new Map<string, number>();
  list: string[] = [];

  get(s: string): number {
    let idx = this.map.get(s);
    if (idx === undefined) {
      idx = this.list.length;
      if (idx > 255) return 0;
      this.map.set(s, idx);
      this.list.push(s);
    }
    return idx;
  }

  write(buf: number[]): void {
    w16be(buf, this.list.length);
    for (const s of this.list) wLpStr(buf, s, 64);
  }
}

/**
 * Scan the arrivals binary for a station slug, filter by route:dir pairs,
 * and return the ultra-lean binary (no colors/headsigns) + generatedAt.
 * Wire format for /a: [count] × ([route lpStr][dir u8][time_mins u16][delay_status s8])
 */
export function scanArrivalsBin(
  bin: Uint8Array,
  slug: string,
  pairs: Array<{ route: string; dir: string }>,
): { buf: Uint8Array; generatedAt: number } | null {
  if (bin.length < 6) return null;

  let pos = 0;
  const generatedAt = ((bin[pos++] << 24) | (bin[pos++] << 16) | (bin[pos++] << 8) | bin[pos++]) >>> 0;

  // Dictionary is in current.bin
  const dictCount = (bin[pos++] << 8) | bin[pos++];
  const dict: string[] = [];
  for (let i = 0; i < dictCount; i++) {
    const len = bin[pos++];
    let s = "";
    for (let j = 0; j < len; j++) s += String.fromCharCode(bin[pos + j]);
    dict.push(s);
    pos += len;
  }

  const numStations = (bin[pos++] << 8) | bin[pos++];

  const pairSet = new Set<string>();
  const routeToId = new Map<string, number>();
  for (let i = 0; i < dict.length; i++) routeToId.set(dict[i], i);
  for (const p of pairs) {
    const rid = routeToId.get(p.route);
    if (rid !== undefined) pairSet.add(`${rid}:${p.dir}`);
  }

  const slugBytes = new TextEncoder().encode(slug);
  let dataOffset = -1;
  for (let i = 0; i < numStations; i++) {
    const slen = bin[pos++];
    let match = slen === slugBytes.length;
    if (match) {
      for (let j = 0; j < slen; j++) if (bin[pos + j] !== slugBytes[j]) { match = false; break; }
    }
    pos += slen;
    const off = ((bin[pos] << 24) | (bin[pos + 1] << 16) | (bin[pos + 2] << 8) | bin[pos + 3]) >>> 0;
    pos += 4;
    if (match) { dataOffset = off; break; }
  }

  if (dataOffset < 0) return null;

  pos = dataOffset;
  const count = (bin[pos++] << 8) | bin[pos++];
  const out: number[] = [];
  let outCount = 0;

  for (let i = 0; i < count && outCount < 10; i++) {
    const routeIdx = bin[pos++];
    const dirCode = bin[pos++];
    const timeMinsHi = bin[pos++];
    const timeMinsLo = bin[pos++];
    const delayStatus = bin[pos++];

    if (!pairSet.has(`${routeIdx}:${dirCode - 0 /* normalize dirCode to ASCII char later? no, it's already ASCII byte */}`)) {
        // Wait, pairSet uses ${rid}:${dir}.
        if (!pairSet.has(`${routeIdx}:${String.fromCharCode(dirCode)}`)) continue;
    }

    const routeStr = dict[routeIdx] || "";
    wLpStr(out, routeStr, 8);
    out.push(dirCode, timeMinsHi, timeMinsLo, delayStatus);
    outCount++;
  }

  return { buf: new Uint8Array([outCount, ...out]), generatedAt };
}

// ─── arrivals/stations.bin ────────────────────────────────────────────────────

export function buildStationsBin(stations: StationWire[], generatedAt: number): Uint8Array {
  const buf: number[] = [];
  w32be(buf, generatedAt);
  w16be(buf, stations.length);
  for (const st of stations) {
    wLpStr(buf, st.k, 39);
    w8(buf, st.r.length);
    for (const rm of st.r) {
      const { r, g, b } = hexToRgb(rm.c);
      w8(buf, r); w8(buf, g); w8(buf, b);
      wLpStr(buf, rm.r, 3);
      w8(buf, rm.d.charCodeAt(0));
      wLpStr(buf, rm.h, 24);
    }
  }
  return new Uint8Array(buf);
}
