/**
 * Binary encoding/decoding for the arrivals and baseline wire formats.
 *
 * baseline.bin layout (Stored in KV, generated by GitHub):
 *   [u32 generated_at]
 *   [u32 base_midnight_utc]
 *   [u16 dict_count]
 *   dictionary: dict_count × ([u8 len][chars])
 *   [u16 station_count]
 *   index: station_count × ([u8 slug_len][slug][u32 data_offset])
 *   data: per station: [u16 count] × ([u8 route_idx][u8 dir][u16 mono_mins][u32 trip_id_hash])
 *
 * arrivals/current.bin layout (Stored in R2, generated by Worker):
 *   [u32 generated_at]
 *   [u16 dict_count]
 *   dictionary: dict_count × ([u8 len][chars])
 *   [u16 num_stations]
 *   index: num_stations × ([u8 slug_len][slug][u32 data_offset])
 *   data:  per station: [u16 count] × ([u8 route_idx][u8 dir][u16 predicted_mins][s8 delay_status])
 *
 * arrivals/stations.bin: (Stored in KV/R2, generated by GitHub)
 *   [u32 generated_at][u16 station_count]
 *   per station: [lpStr slug][u8 route_count] × ([u8 r,g,b][lpStr route][u8 dir][lpStr headsign])
 */

export interface StationWire {
  k: string;
  r: Array<{ r: string; c: string | null; d: string; h: string }>;
}

// ─── Low-level writers ────────────────────────────────────────────────────────

export function w8(buf: number[], v: number): void { buf.push(v & 0xFF); }
export function w16(buf: number[], v: number): void { buf.push(v & 0xFF, (v >>> 8) & 0xFF); }
export function w32(buf: number[], v: number): void {
  buf.push(v & 0xFF, (v >>> 8) & 0xFF, (v >>> 16) & 0xFF, (v >>> 24) & 0xFF);
}
export function wLpStr(buf: number[], s: string, maxLen: number): void {
  const t = s.slice(0, maxLen);
  buf.push(Math.min(t.length, 255));
  for (let i = 0; i < t.length; i++) buf.push(t.charCodeAt(i) & 0xFF);
}

export function hexToRgb(c: string | null): { r: number; g: number; b: number } {
  if (!c) return { r: 0x88, g: 0x88, b: 0x88 };
  const v = parseInt(c.replace("#", ""), 16);
  if (isNaN(v)) return { r: 0x88, g: 0x88, b: 0x88 };
  return { r: (v >>> 16) & 0xFF, g: (v >>> 8) & 0xFF, b: v & 0xFF };
}

// ─── Hash for Trip IDs (32-bit FNV-1a) ────────────────────────────────────────

export function hashTripId(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

export function hashTripIdBytes(buf: Uint8Array, start: number, len: number): number {
  let h = 0x811c9dc5;
  const end = start + len;
  for (let i = start; i < end; i++) {
    h ^= buf[i];
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

// ─── Dictionary Encoding ──────────────────────────────────────────────────────

export class Dictionary {
  map = new Map<string, number>();
  list: string[] = [];

  get(s: string): number {
    let idx = this.map.get(s);
    if (idx === undefined) {
      idx = this.list.length;
      if (idx > 255) return 0;
      this.map.set(s, idx);
      this.list.push(s);
    }
    return idx;
  }

  write(buf: number[]): void {
    w16(buf, this.list.length);
    for (const s of this.list) wLpStr(buf, s, 64);
  }
}

/**
 * Scan the arrivals binary for a station slug, filter by route:dir pairs,
 * and return the ultra-lean binary (no colors/headsigns) + generatedAt.
 * Wire format for /a: [count] × ([route lpStr][dir u8][time_mins u16][delay_status s8])
 */
export function scanArrivalsBin(
  bin: Uint8Array,
  slug: string,
  pairs: Array<{ route: string; dir: string }>,
): { buf: Uint8Array; generatedAt: number } | null {
  if (bin.length < 10) return null;

  let pos = 0;
  const generatedAt = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
  const baseMidnightUTC = (bin[pos++] | (bin[pos++] << 8) | (bin[pos++] << 16) | (bin[pos++] << 24)) >>> 0;
  const cutoffMonoMins = Math.floor((Date.now() / 1000 - baseMidnightUTC) / 60) - 5;

  // Dictionary stored as offsets — no string allocation
  const dictCount = bin[pos++] | (bin[pos++] << 8);
  const dictOffsets: number[] = [];
  for (let i = 0; i < dictCount; i++) {
    const len = bin[pos++];
    dictOffsets.push(pos);
    pos += len;
  }

  const numStations = bin[pos++] | (bin[pos++] << 8);

  let dataOffset = -1;
  for (let i = 0; i < numStations; i++) {
    const slen = bin[pos++];
    let match = slen === slug.length;
    if (match) {
      for (let j = 0; j < slen; j++) if (bin[pos + j] !== slug.charCodeAt(j)) { match = false; break; }
    }
    pos += slen;
    const off = (bin[pos] | (bin[pos + 1] << 8) | (bin[pos + 2] << 16) | (bin[pos + 3] << 24)) >>> 0;
    pos += 4;
    if (match) { dataOffset = off; break; }
  }

  if (dataOffset < 0) return null;

  pos = dataOffset;
  const count = bin[pos++] | (bin[pos++] << 8);
  const out: number[] = [];
  let outCount = 0;

  for (let i = 0; i < count && outCount < 10; i++) {
    const routeIdx = bin[pos++];
    const dirCode = bin[pos++];
    const monoMins = bin[pos++] | (bin[pos++] << 8);
    const delayStatus = bin[pos++];

    if (monoMins < cutoffMonoMins) continue;

    const dirChar = String.fromCharCode(dirCode);

    // Byte-compare route against dictionary — avoids string allocation
    let pairMatch = false;
    for (let j = 0; j < pairs.length; j++) {
      const p = pairs[j];
      if (p.dir !== dirChar) continue;
      const dOff = dictOffsets[routeIdx];
      const dLen = bin[dOff - 1];
      if (dLen !== p.route.length) continue;
      let match = true;
      for (let k = 0; k < dLen; k++) {
        if (bin[dOff + k] !== p.route.charCodeAt(k)) { match = false; break; }
      }
      if (match) { pairMatch = true; break; }
    }
    if (!pairMatch) continue;

    const dOff = dictOffsets[routeIdx];
    const dLen = bin[dOff - 1];
    const timeMins = monoMins % 1440;
    out.push(dLen);
    for (let k = 0; k < dLen; k++) out.push(bin[dOff + k]);
    out.push(dirCode, (timeMins >>> 8) & 0xFF, timeMins & 0xFF, delayStatus);
    outCount++;
  }

  const res = new Uint8Array(out.length + 1);
  res[0] = outCount;
  for (let i = 0; i < out.length; i++) res[i + 1] = out[i];
  return { buf: res, generatedAt };
}

// ─── arrivals/stations.bin ────────────────────────────────────────────────────

export function buildStationsBin(stations: StationWire[], generatedAt: number): Uint8Array {
  const buf: number[] = [];
  w32(buf, generatedAt);
  w16(buf, stations.length);
  for (const st of stations) {
    wLpStr(buf, st.k, 39);
    w8(buf, st.r.length);
    for (const rm of st.r) {
      const { r, g, b } = hexToRgb(rm.c);
      w8(buf, r); w8(buf, g); w8(buf, b);
      wLpStr(buf, rm.r, 3);
      w8(buf, rm.d.charCodeAt(0));
      wLpStr(buf, rm.h, 24);
    }
  }
  return new Uint8Array(buf);
}
